apiVersion: v1
kind: Pod
metadata:
  name: nginx03
  lables:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd04
  lables:
    app: httpd

spec:
  containers:
    - name: httpd
      image: httpd