apiVersion: v1
kind: Pod
metadata:
  name: cm01
data:
  URL: www.com
  name: manoj
  from: mncl

---
apiVersion: v1
kind: Pod
metadata:
  name: cm01
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name:cm01
