apiVersion: v1
kind: configMap
metadata:
  name: cm01
data:
  URL: www.com
  SUB_URL: sub_example.com
  DOMAIN: .com

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx06
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: cm01
