apiVersion: v1
kind: Pod
metadata:
  name: cm01
data:
  URL: www.com
  name: manoj.com
  from: mncl.com

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx06
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name:cm01
