apiVersion: v1
kind: Secret
metadata:
  name: secret01
data:
  URL: d3d3LmNvbQ==
  SUB_URL: c3ViX2V4YW1wbGUuY29t
  DOMAIN: LmNvbQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx08
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - SecretRef:
            name: secret01
